# Generated by Django 4.0.2 on 2022-02-10 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名')),
                ('order_num', models.IntegerField(verbose_name='序号')),
            ],
            options={
                'db_table': 't_category',
                'ordering': ['-order_num'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '客户管理', 'verbose_name_plural': '客户管理'},
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='水果名')),
                ('price', models.FloatField(verbose_name='价格')),
                ('source', models.CharField(max_length=30, verbose_name='原产地')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.catetype')),
            ],
            options={
                'verbose_name': '水果表',
                'verbose_name_plural': '水果表',
                'db_table': 't_fruit',
            },
        ),
    ]
