# Generated by Django 4.0.2 on 2022-02-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_catetype_alter_user_options_alter_user_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catetype',
            options={'ordering': ['-order_num'], 'verbose_name': '水果分类', 'verbose_name_plural': '水果分类'},
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50, unique=True, verbose_name='店名')),
                ('store_type', models.IntegerField(choices=[(0, '自营'), (1, '第三方')], verbose_name='类型')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='城市')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='成立时间')),
                ('last_time', models.DateField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '水果店',
                'verbose_name_plural': '水果店',
                'db_table': 't_store',
                'unique_together': {('name', 'city')},
            },
        ),
    ]
