# Generated by Django 4.0.2 on 2022-02-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_catetype_options_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='store', verbose_name='logo', width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_height',
            field=models.IntegerField(null=True, verbose_name='logo高度'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_width',
            field=models.IntegerField(null=True, verbose_name='logo宽度'),
        ),
        migrations.AddField(
            model_name='store',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='store',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='成立时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='last_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='最后修改时间'),
        ),
    ]
