# Generated by Django 4.0.2 on 2022-02-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_tag_alter_fruit_category_alter_fruit_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='口令'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='mainapp.catetype'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='t_fruit_tags', null=True, related_name='fruits', to='mainapp.Tag', verbose_name='所有标签'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='users',
            field=models.ManyToManyField(blank=True, db_table='t_collect', null=True, related_name='fruits', to='mainapp.User', verbose_name='收藏用户列表'),
        ),
    ]
